### ISSUE TITLE
errors in PowerShell

### ISSUE THREAD

**Issue by lewwwin** [FebVeg/Rubber-Ducky-Payloads#1]
Does this payload work? I launched it, but in PowerShell I get these errors:
```
At line:1 char:1
+ @[console]::WindowWidth=5; [console]::WindowHeight=1; [console]::Buff ...
+ ~
Unrecognized token in source text.
At line:1 char:100
+ ... sole]::WindowHeight=1; [console]::BufferWidth=[console]::WindowWidth@
+                                                                         ~
Unrecognized token in source text.
At line:1 char:100
+ ... sole]::WindowHeight=1; [console]::BufferWidth=[console]::WindowWidth@
+                                                                         ~
Unexpected token '@' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnrecognizedToken
```

**Comment by FebVeg** [comment]
Hi,
It works, the first line is: 
`powershell -noexit -command "[console]::WindowWidth=5; [console]::WindowHeight=1; [console]::BufferWidth=[console]::WindowWidth"
DELAY 500`

![github](https://user-images.githubusercontent.com/25832419/73454827-2df9d500-436f-11ea-9873-d64043339d2c.PNG)
![github2](https://user-images.githubusercontent.com/25832419/73454828-2df9d500-436f-11ea-8838-335270869774.PNG)

try to open a run command on windows (press WINDOWS + R) paste the string and press ENTER.
